DROP DATABASE IF EXISTS GiaCongStore;
create database GiaCongStore;
  
use GiaCongStore;

CREATE TABLE NHACUNGCAP(
	MNCC VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNHACUNGCAP NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	SDT CHAR(50) NOT NULL CHECK (SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or 
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	ACTIVATE BIT NOT NULL DEFAULT 1,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE TAIKHOAN(
	TAIKHOAN VARCHAR(30) NOT NULL PRIMARY KEY,
	MATKHAU VARCHAR (30) NOT NULL,
	ACTIVATE BIT NOT NULL DEFAULT 0,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE CHUCVU(
	MCV VARCHAR(10) NOT NULL PRIMARY KEY,
	TENCHUCVU NVARCHAR(100) NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE KHACHHANG(
	MKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENKHACHHANG NVARCHAR(100) NOT NULL,
	SDT CHAR(50) NOT NULL CHECK (SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or 
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONGTY NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	ACTIVATE BIT NOT NULL DEFAULT 1,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE LOAIQUYTRINH(
	MLQT VARCHAR(10) NOT NULL PRIMARY KEY,
	TENLOAIQUYTRINH NVARCHAR(100) NOT NULL,
	NGUOITAO VARCHAR(10) NOT NULL,
	ACTIVATE BIT NOT NULL DEFAULT 1,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE CHEDOCAT(
	MCDC VARCHAR(10) NOT NULL PRIMARY KEY,
	MSP VARCHAR(10),
	TENCHEDOCAT NVARCHAR(100) NOT NULL,
	SOVONGQUAY FLOAT DEFAULT 0,
	BUOCTIEN FLOAT DEFAULT 0,
	CHIEUSAUCAT FLOAT DEFAULT 0,
	CHIEUDAILAMVIEC FLOAT DEFAULT 0,
	THOIGIANHOANTHANH FLOAT DEFAULT 0,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE BANVE(
	MBV VARCHAR(10) NOT NULL PRIMARY KEY,
	MKH VARCHAR(10) NOT NULL,
	MNVNBV VARCHAR(10) NOT NULL,
	TENBANVE NVARCHAR(100) NOT NULL,
	NGAYNHAN DATETIME NOT NULL,
	NGAYHOANTHANH DATETIME NOT NULL,
	NGAYKHAIPHAT DATETIME NOT NULL,
	GHICHU NVARCHAR(100) NOT NULL,
	ACTIVATE BIT NOT NULL DEFAULT 1,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE QUYTRINH(
	MQT VARCHAR(10) NOT NULL PRIMARY KEY,
	MBV VARCHAR(10) NOT NULL,
	MCDC VARCHAR(10) NOT NULL,
	MLQT VARCHAR(10) NOT NULL,
	MNV VARCHAR(10) NOT NULL,
	TENQUYTRINH NVARCHAR(100) NOT NULL,
	DONE BIT NOT NULL DEFAULT 1,
	THOIDIEMHOANTHANH DATETIME NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)
   
CREATE TABLE LOAISANPHAM(
	MLSP VARCHAR(10) PRIMARY KEY NOT NULL,
	TENLOAI NVARCHAR(100) NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP
)
 
CREATE TABLE NHANVIEN(
	MNV VARCHAR(10) PRIMARY KEY NOT NULL,
    TAIKHOAN VARCHAR(30),
    TENNV NVARCHAR(100) NOT NULL,
    GIOITINH BIT NOT NULL DEFAULT 0,
	NGAYSINH DATE NOT NULL, -- yyyy/mm/dd
    CMND VARCHAR(13) UNIQUE NOT NULL CHECK (CMND like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
											or CMND like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
											or CMND like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
											or CMND like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    DIACHI NVARCHAR(100) NOT NULL,
    SDT CHAR(50) NOT NULL CHECK (SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or 
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' or
								SDT like '+84[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    EMAIL NVARCHAR(50),
    NGAYVAOLAM DATE NOT NULL,
    CHUCVU VARCHAR(10) NOT NULL,
    CALAMVIEC VARCHAR(10) NOT NULL,
    TIENLUONG INT NOT NULL DEFAULT 0,
	ACTIVATE BIT NOT NULL DEFAULT 1,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE SANPHAM(
	MSP VARCHAR(10) PRIMARY KEY NOT NULL,
	TENSANPHAM NVARCHAR(50) NOT NULL,
	DONVITINH NVARCHAR(15) NOT NULL, 
	CODE VARCHAR(50) NOT NULL,
	SOLUONG INT NOT NULL DEFAULT 0,
	QUYCACH INT NOT NULL DEFAULT 0,
	HINHANH VARCHAR NOT NULL,
	ACTIVATE BIT NOT NULL DEFAULT 0,
	NHACUNGCAP VARCHAR(10) NOT NULL,
	LOAISANPHAM VARCHAR(10) NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP) 

CREATE TABLE TRANGTHAINHAPXUAT(
	MTTNX VARCHAR(10) PRIMARY KEY NOT NULL,
	TENTRANGTHAI NVARCHAR(20) NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP) 

CREATE TABLE PHIEUNHAP(
	MPN VARCHAR(10) PRIMARY KEY NOT NULL,
	TRANGTHAINHAPXUAT VARCHAR(10) NOT NULL,
	NHANVIEN VARCHAR(10) NOT NULL,
	NGAYNHAP DATETIME DEFAULT CURRENT_TIMESTAMP,
	TONGSOLUONGNHAP INT NOT NULL DEFAULT 0,
	GHICHU NVARCHAR(1000),
	LICHSUTRANGTHAINHAP NVARCHAR(1000)) 

CREATE TABLE CHITIETPHIEUNHAP(
	MPN VARCHAR(10) NOT NULL, 
	MSP VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL DEFAULT 0,
	DONGIA INT NOT NULL DEFAULT 0,
	PRIMARY KEY (MPN,MSP)) 

CREATE TABLE CHITIETPHIEUXUAT(
	MPX VARCHAR(10) NOT NULL, 
	MSP VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL DEFAULT 0,
	PRIMARY KEY (MPX,MSP)) 

CREATE TABLE PHIEUXUAT(
	MPX VARCHAR(10) PRIMARY KEY NOT NULL,
	TRANGTHAINHAPXUAT VARCHAR(10) NOT NULL,
	NHANVIEN VARCHAR(10) NOT NULL,
	NGAYXUAT DATETIME DEFAULT CURRENT_TIMESTAMP,
	TONGSOLUONGXUAT INT NOT NULL DEFAULT 0,
	GHICHU NVARCHAR(1000),
	LICHSUTRANGTHAIXUAT NVARCHAR(1000)) 

CREATE TABLE CALAMVIEC(
	MC VARCHAR(10) NOT NULL PRIMARY KEY,
	TENCA NVARCHAR(20) NOT NULL,
	TU NVARCHAR(10) NOT NULL,
	DEN NVARCHAR(10) NOT NULL,
	NGAYKHOITAO DATETIME DEFAULT CURRENT_TIMESTAMP)
	 
CREATE TABLE CHITIETNGUOITHAMGIABANVE(
	MBV VARCHAR(10) NOT NULL,
	MNV VARCHAR(10) NOT NULL,
	CHUCVUTRONGBANVE VARCHAR(10) NOT NULL,
	GHICHU NVARCHAR(1000),
	PRIMARY KEY (MBV,MNV)
)

CREATE TABLE CHITIETSANPHAMDUKIENBANVE(
	MBV VARCHAR(10) NOT NULL,
	MSP VARCHAR(10) NOT NULL,
	SOLUONGDUKIEN INT NOT NULL DEFAULT 0,
	SOLUONGDASUDUNG INT NOT NULL DEFAULT 0,
	GHICHU NVARCHAR(1000),
	PRIMARY KEY (MBV,MSP)
)
 
CREATE TABLE CHITIETNGUOITHAMGIAQUYTRINH(
	MQT VARCHAR(10) NOT NULL,
	MNV VARCHAR(10) NOT NULL,
	CHUCVUTRONGQUYTRINH VARCHAR(10) NOT NULL,
	GHICHU NVARCHAR(1000),
	PRIMARY KEY (MQT,MNV)
)

CREATE TABLE CHITIETSANPHAMQUYTRINH(
	MQT VARCHAR(10) NOT NULL,
	MSP VARCHAR(10) NOT NULL,
	SOLUONGDUKIEN INT NOT NULL DEFAULT 0,
	SOLUONGDASUDUNG INT NOT NULL DEFAULT 0,
	GHICHU NVARCHAR(1000),
	PRIMARY KEY (MQT,MSP)
)



-- THEM KHOA NGOAI

ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_NHACUNGCAP FOREIGN KEY (NHACUNGCAP) REFERENCES NHACUNGCAP(MNCC)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_LOAISANPHAM FOREIGN KEY (LOAISANPHAM) REFERENCES LOAISANPHAM(MLSP)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_TAIKHOAN FOREIGN KEY (TAIKHOAN) REFERENCES TAIKHOAN(TAIKHOAN) 
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHUCVU FOREIGN KEY (CHUCVU) REFERENCES CHUCVU(MCV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CALAMVIEC FOREIGN KEY (CALAMVIEC) REFERENCES CALAMVIEC(MC)

ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PHIEUNHAP_TRANGTHAINHAPXUAT FOREIGN KEY (TRANGTHAINHAPXUAT) REFERENCES TRANGTHAINHAPXUAT(MTTNX)  
ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PHIEUNHAP_NHANVIEN FOREIGN KEY (NHANVIEN) REFERENCES NHANVIEN(MNV)  

ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT FK_CHITIETPHIEUNHAP_PHIEUNHAP FOREIGN KEY (MPN) REFERENCES PHIEUNHAP(MPN)  
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT FK_CHITIETPHIEUNHAP_SANPHAM FOREIGN KEY (MSP) REFERENCES SANPHAM(MSP)  
 
ALTER TABLE PHIEUXUAT ADD CONSTRAINT FK_PHIEUXUAT_TRANGTHAINHAPXUAT FOREIGN KEY (TRANGTHAINHAPXUAT) REFERENCES TRANGTHAINHAPXUAT(MTTNX)  
ALTER TABLE PHIEUXUAT ADD CONSTRAINT FK_PHIEUXUAT_NHANVIEN FOREIGN KEY (NHANVIEN) REFERENCES NHANVIEN(MNV)  

ALTER TABLE CHITIETPHIEUXUAT ADD CONSTRAINT FK_CHITIETPHIEUXUAT_PHIEUXUAT FOREIGN KEY (MPX) REFERENCES PHIEUXUAT(MPX)  
ALTER TABLE CHITIETPHIEUXUAT ADD CONSTRAINT FK_CHITIETPHIEUXUAT_SANPHAM FOREIGN KEY (MSP) REFERENCES SANPHAM(MSP)  

ALTER TABLE BANVE ADD CONSTRAINT FK_BANVE_KHACHHANG FOREIGN KEY (MBV) REFERENCES KHACHHANG(MKH)
ALTER TABLE BANVE ADD CONSTRAINT FK_BANVE_NHANVIEN FOREIGN KEY (MNVNBV) REFERENCES NHANVIEN(MNV)

ALTER TABLE QUYTRINH ADD CONSTRAINT FK_QUYTRINH_NHANVIEN FOREIGN KEY (MNV) REFERENCES NHANVIEN(MNV)
ALTER TABLE QUYTRINH ADD CONSTRAINT FK_QUYTRINH_BANVE FOREIGN KEY (MBV) REFERENCES BANVE(MBV)
ALTER TABLE QUYTRINH ADD CONSTRAINT FK_QUYTRINH_LOAIQUYTRINH FOREIGN KEY (MLQT) REFERENCES LOAIQUYTRINH(MLQT)
ALTER TABLE QUYTRINH ADD CONSTRAINT FK_QUYTRINH_CHEDOCAT FOREIGN KEY (MCDC) REFERENCES CHEDOCAT(MCDC)

ALTER TABLE CHITIETNGUOITHAMGIABANVE ADD CONSTRAINT FK_CHITIETNGUOITHAMGIABANVE_NHANVIEN FOREIGN KEY (MNV) REFERENCES NHANVIEN(MNV)
ALTER TABLE CHITIETNGUOITHAMGIABANVE ADD CONSTRAINT FK_CHITIETNGUOITHAMGIABANVE_BANVE FOREIGN KEY (MBV) REFERENCES BANVE(MBV)
ALTER TABLE CHITIETNGUOITHAMGIABANVE ADD CONSTRAINT FK_CHITIETNGUOITHAMGIABANVE_CHUCVU FOREIGN KEY (CHUCVUTRONGBANVE) REFERENCES CHUCVU(MCV)
 
ALTER TABLE CHITIETSANPHAMDUKIENBANVE ADD CONSTRAINT FK_CHITIETSANPHAMDUKIENBANVE_BANVE FOREIGN KEY (MBV) REFERENCES BANVE(MBV)
ALTER TABLE CHITIETSANPHAMDUKIENBANVE ADD CONSTRAINT FK_CHITIETSANPHAMDUKIENBANVE_SANPHAM FOREIGN KEY (MSP) REFERENCES SANPHAM(MSP)

ALTER TABLE CHITIETNGUOITHAMGIAQUYTRINH ADD CONSTRAINT FK_CHITIETNGUOITHAMGIAQUYTRINH_CHUCVU FOREIGN KEY (CHUCVUTRONGQUYTRINH) REFERENCES CHUCVU(MCV)
ALTER TABLE CHITIETNGUOITHAMGIAQUYTRINH ADD CONSTRAINT FK_CHITIETNGUOITHAMGIAQUYTRINH_QUYTRINH FOREIGN KEY (MQT) REFERENCES QUYTRINH(MQT)
ALTER TABLE CHITIETNGUOITHAMGIAQUYTRINH ADD CONSTRAINT FK_CHITIETNGUOITHAMGIAQUYTRINH_NHANVIEN FOREIGN KEY (MNV) REFERENCES NHANVIEN(MNV)
 
ALTER TABLE CHITIETSANPHAMQUYTRINH ADD CONSTRAINT FK_CHITIETSANPHAMQUYTRINH_QUYTRINH FOREIGN KEY (MQT) REFERENCES QUYTRINH(MQT)
ALTER TABLE CHITIETSANPHAMQUYTRINH ADD CONSTRAINT FK_CHITIETSANPHAMQUYTRINH_SANPHAM FOREIGN KEY (MSP) REFERENCES SANPHAM(MSP)


INSERT INTO CHUCVU(MCV,TENCHUCVU) VALUES 
			('CV00000001','admin'),
			('CV00000002','user'),
			('CV00000003','leadbanve'),
			('CV00000004','memberbanve'),
			('CV00000005','leadquytrinh'),
			('CV00000006','memberquytrinh')

INSERT INTO CALAMVIEC(MC,TENCA, TU, DEN) VALUES 
			('CLV0000001',N'Cả ngày','8h','20h'),
			('CLV0000002',N'Sáng - Tối','8h','20h'),
			('CLV0000003',N'Tối - Sáng','20h','8h') 

SELECT * FROM CALAMVIEC			