//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANVE()
        {
            this.CHITIETNGUOITHAMGIABANVEs = new HashSet<CHITIETNGUOITHAMGIABANVE>();
            this.CHITIETSANPHAMDUKIENBANVEs = new HashSet<CHITIETSANPHAMDUKIENBANVE>();
            this.QUYTRINHs = new HashSet<QUYTRINH>();
        }
    
        public string MBV { get; set; }
        public string MKH { get; set; }
        public string MNVNBV { get; set; }
        public string TENBANVE { get; set; }
        public System.DateTime NGAYNHAN { get; set; }
        public System.DateTime NGAYHOANTHANH { get; set; }
        public System.DateTime NGAYKHAIPHAT { get; set; }
        public string GHICHU { get; set; }
        public bool ACTIVATE { get; set; }
        public Nullable<System.DateTime> NGAYKHOITAO { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNGUOITHAMGIABANVE> CHITIETNGUOITHAMGIABANVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAMDUKIENBANVE> CHITIETSANPHAMDUKIENBANVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYTRINH> QUYTRINHs { get; set; }
    }
}
