//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNGUOITHAMGIABANVE
    {
        public string MBV { get; set; }
        public string MNV { get; set; }
        public string CHUCVUTRONGBANVE { get; set; }
        public string GHICHU { get; set; }
    
        public virtual BANVE BANVE { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
