//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUAT
    {
        public string MPX { get; set; }
        public string MSP { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
