//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string MKH { get; set; }
        public string TENKHACHHANG { get; set; }
        public string SDT { get; set; }
        public string CONGTY { get; set; }
        public string DIACHI { get; set; }
        public bool ACTIVATE { get; set; }
        public Nullable<System.DateTime> NGAYKHOITAO { get; set; }
    
        public virtual BANVE BANVE { get; set; }
    }
}
