//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGHISTORY
    {
        public string MLOG { get; set; }
        public string CODE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> NGAYKHOITAO { get; set; }
    }
}
