//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUYTRINH()
        {
            this.CHITIETNGUOITHAMGIAQUYTRINHs = new HashSet<CHITIETNGUOITHAMGIAQUYTRINH>();
            this.CHITIETSANPHAMQUYTRINHs = new HashSet<CHITIETSANPHAMQUYTRINH>();
        }
    
        public string MQT { get; set; }
        public string MBV { get; set; }
        public string MCDC { get; set; }
        public string MLQT { get; set; }
        public string MNV { get; set; }
        public string TENQUYTRINH { get; set; }
        public bool DONE { get; set; }
        public System.DateTime THOIDIEMHOANTHANH { get; set; }
        public Nullable<System.DateTime> NGAYKHOITAO { get; set; }
    
        public virtual BANVE BANVE { get; set; }
        public virtual CHEDOCAT CHEDOCAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNGUOITHAMGIAQUYTRINH> CHITIETNGUOITHAMGIAQUYTRINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAMQUYTRINH> CHITIETSANPHAMQUYTRINHs { get; set; }
        public virtual LOAIQUYTRINH LOAIQUYTRINH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
