//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaCongThienStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
            this.CHITIETSANPHAMDUKIENBANVEs = new HashSet<CHITIETSANPHAMDUKIENBANVE>();
            this.CHITIETSANPHAMQUYTRINHs = new HashSet<CHITIETSANPHAMQUYTRINH>();
        }
    
        public string MSP { get; set; }
        public string TENSANPHAM { get; set; }
        public string DONVITINH { get; set; }
        public string CODE { get; set; }
        public int SOLUONG { get; set; }
        public string QUYCACH { get; set; }
        public double DTRONG { get; set; }
        public double DNGOAI { get; set; }
        public double LCHIEUDAI { get; set; }
        public double PHIDUONGKINH { get; set; }
        public double RBANKINH { get; set; }
        public string PBUOCREN { get; set; }
        public string GHICHU { get; set; }
        public string HINHANH { get; set; }
        public bool ACTIVATE { get; set; }
        public string MNCC { get; set; }
        public string MLSP { get; set; }
        public Nullable<System.DateTime> NGAYKHOITAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAMDUKIENBANVE> CHITIETSANPHAMDUKIENBANVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAMQUYTRINH> CHITIETSANPHAMQUYTRINHs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
